plugins { id 'com.android.application' }

android {
    namespace 'com.example.virtualbuttons'
    compileSdk 36

    defaultConfig {
        applicationId 'com.example.virtualbuttons'
        minSdk 26
        targetSdk 36
        versionCode 1
        versionName '1.0.0'
    }

    buildTypes {
        debug {
            applicationIdSuffix ""
            archiveFileName = "VirtualButtons.apk"
        }
    }
}
